### ISSUE TITLE
Postgresql support on RDS

### ISSUE THREAD

**Issue by AmiZya** [Miserlou/django-zappa#3]
Hello,

Is there anyone working on postgresql support on RDS ? If not I can try to make it work and submit a pull request.

Thanks

Amine

**Comment by Miserlou** [comment]
Hey Amine!

That sounds good. It should be totally possible to get PG working with Zappa, I just haven't tried it yet.

The only issue it that we'll need to either:

- Find a pure-Python Postgres Django backend (ala MySQL-Connector)

or

- Come up with some way of distributing the pre-compiled .so files for the x86_64 linux platform into the Zappa zip file so that it JustWorks.

Maybe do some research into the first approach, and if there's nothing there we can think about the second?

Would love to have this sorted out, thanks for volunteering.

**Comment by chrismccracken** [comment]
I started looking at this same issue, and found this that may help https://github.com/jkehler/awslambda-psycopg2 django-zappa looks great by the way, can't wait to give it a try!

**Comment by Miserlou** [comment]
Oh, excellent.

Has anybody actually tried any of these Python PSQL libraries yet?

**Comment by Miserlou** [comment]
So, I'm not sure if that's the right solution as it still uses a compiled .so file - I'd prefer to keep everything in pure Python to avoid having to deal with injecting precompiled binary objects as part of the Zappa deployment.

There are some pretty good looking pure python PG adapters:
https://github.com/mfenniak/pg8000
https://github.com/d33tah/bpgsql

BPGSQL looks like it has had some work done towards a Django adapter, but unfortunately is looks like the maintainer just quite the project _yesterday_, which is very unfortunate.

**Comment by d33tah** [comment]
I'm the maintainer of BPGSQL - the discussion is about the project security, feel invited to take a look at d33tah/bpgsql#7 for details.

**Comment by stringfellow** [comment]
:+1: from me folks, very excited about the prospects of using django-zappa (to replace celery... is that sane?). Definitely needs Postgres support though :) Watching with interest.

**Comment by Miserlou** [comment]
The Celery idea is absolutely on the roadmap, I'm going to open up another ticket to discuss that.

**Comment by cancan101** [comment]
This post talks about dealing so's on Lambda: https://serverlesscode.com/post/deploy-scikitlearn-on-lamba/

**Comment by Miserlou** [comment]
Django-Zappa now supports Postgres via Lambda-Packages as of version 0.12.0.

**Comment by stringfellow** [comment]
Tremendously exciting! Thanks!
