### ISSUE TITLE
urls module not found

### ISSUE THREAD

**Issue by scott2b** [Miserlou/django-zappa#49]
It is unclear to me how the PYTHONPATH and general environment are setup. I can successfully deploy an application to Lambda, however the deployed Django is unable to find the urls file.

I have, for example, project myproject, with core application myproject (the standard Django setup) which contains urls.py. Thus, the settings files have:

ROOT_URLCONF = 'myproject.urls'

But (in debug mode) I am getting: No module named myproject.urls

The settings I am using work find when running locally. My suspicion is that the PYTHONPATH is not being set so that myproject is available on the path, but this is just a guess really. I noted that the test settings file has BASE_DIR set to an empty string, which strikes me as unusual, but I have no idea if that is related to this. Setting BASE_DIR empty in my own project breaks the update process for me with a botocore function not found error.

**Comment by scott2b** [comment]
I have started a new project from scratch and am not seeing this issue. Not sure what I did in my other project to mess things up. Closing this as a non-issue.

**Comment by bjinwright** [comment]
I got this one as well. It is not including the package created by the django-admin startproject <project_name> command. Only the packages that are in the installed apps.

**Comment by Miserlou** [comment]
Just out of curiosity (and perhaps relevance) - what was the name of the project you created?

Zappa core had some major upgrades recently, and Django-Zappa hasn't caught up yet. Hopefully I can address this today, more details on your setups would be helpful!

**Comment by Tjorriemorrie** [comment]
I'm experiencing this issue for a new project from scratch.

[url](https://merwp4pq56.execute-api.ap-southeast-2.amazonaws.com/dev)
```
ModuleNotFoundError at /

No module named 'ontback.urls'
```

Zappa settings:
```
{
    "dev": {
        "aws_region": "ap-southeast-2",
        "django_settings": "ontback.ontback.settings",
        "profile_name": "ontmoetuser",
        "project_name": "ontmoet",
        "runtime": "python3.6",
        "s3_bucket": "zappa-8lzcu4ugl"
    }
}
```

Can anyone help please?

**Comment by vidalon** [comment]
Answering this in hopes that people having the same issue can find this thread. 

The problem that @Tjorriemorrie was experiencing has to do with having created the Django project in a folder that already existed: `ontback`. That is why you get a folder structure like so: `ontback/ontback/settings.py`

Python modules require a __init__.py file per folder level. In this case what happened is that you get a __init__.py file on the innermost `ontback` folder created by the `startproject` command but since you ran it inside an existing folder that was not a Python module, you get this error.

The way to fix it is to move all your Django project files to the parent folder and avoid the double nesting generated by running `django startproject` inside an existing folder with the same name.

In this case: 

`mv ontback ontback.old`
`mv ontback.old/* .`
`rm -r ontback`

**Comment by loscil06** [comment]
> ...
> The way to fix it is to move all your Django project files to the parent folder and avoid the double nesting generated by running `django startproject` inside an existing folder with the same name.
> 
> In this case:
> 
> `mv ontback ontback.old`
> `mv ontback.old/* .`
> `rm -r ontback`

This solved my issue, thanks!
Just remember to configure `settings.py ` and `manage.py` to reflect the new path of the config files.
