### ISSUE TITLE
Not including the package created by the django-admin startproject command.

### ISSUE THREAD

**Issue by bjinwright** [Miserlou/django-zappa#53]
The deploy and update command is not including the package created by the django-admin startproject command. Only the packages that are in the installed apps. This results in a <project_name>.urls import error. No module found zipzip.urls

**Comment by Miserlou** [comment]
Ha!

I thought this was going to be the issue! This bit me before because I had a package called "environmental".

So, you can probably guess what's going on here - this is a regular expression bug! Zappa is excluding "zip" files a bit too aggressively!

This is fixed in the latest Zappa core, but the published version of Django-Zappa is behind in its requirements. This should be fixed, hopefully today, along with quite a few other fixes.

**Comment by bjinwright** [comment]
Ahhhhhh!! Thanks for the quick response.

**Comment by Miserlou** [comment]
No problem! Thanks for using Zappa - let me know if there's anything else that I can help with. As you can tell, this project is still pretty young, so early users can have a huge influence of finding and fixing bugs, documentation, guides, etcetera. 

I'm going to re-open this ticket and leave it open until I push a fix for the regex issues. You can remove your self from the ticket if you don't want to receive notifications.

**Comment by Miserlou** [comment]
Should be fixed in 0.13.0
